title: "αβ"
locale: en-US
description: Bonneville or Bust
timezone: "America/New_York"

# the base hostname & protocol for your site, e.g. http://example.com
url: https://beta5.org

# the subpath of your site, e.g. /blog
baseurl: "/"

static_images_base_url: http://static.images.alpha.beta5.org

## maps to _data/authors.yaml
author: blalor@bravo5.org

permalink: /:categories/:year-:month-:day-:title.html
#category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

theme: jekyll-theme-so-simple

plugins:
  - jekyll-feed
